NMI_{0}  
	
	LDA MODULATION_ADDRESS
	LDA CARTRIDGE_BANK_VALUE
	STA {1}	
	
	LDA MODULATION_ADDRESS	
	LDA CARTRIDGE_BANK_VALUE
	STA {2}		
	
	LDA MODULATION_ADDRESS	
	LDA CARTRIDGE_BANK_VALUE
	STA {3}	
	
	LDA MODULATION_ADDRESS	
	LDA CARTRIDGE_BANK_VALUE
	STA {4}	
	
	LDA MODULATION_ADDRESS	
	LDA CARTRIDGE_BANK_VALUE
	STA {5}	
	
	LDA MODULATION_ADDRESS	
	LDA CARTRIDGE_BANK_VALUE
	STA {6}	
	
	LDA MODULATION_ADDRESS	
	LDA CARTRIDGE_BANK_VALUE
	STA {7}		
	
	LDA MODULATION_ADDRESS	
	LDA CARTRIDGE_BANK_VALUE
	STA {8}		
								
